oneplace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('scrapping.urls')),
    path('report/', include('report.urls')),
    path('accounts/', include('accounts.urls'))
]

report/urls.py
from django.urls import path
from . import views

app_name = 'report'

urlpatterns = [
    path('', views.show, name='show'),
    path('report-data', views.report_data, name='report_data'),
    path('add-application', views.add_application, name='add_application'),
    path('applications/<int:pk>/change-status', views.change_status, name='change_status'),
    path('report/export', views.export, name='export')
]

report/models.py
from django.db import models
from accounts.models import User

class SavedJob(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    company = models.CharField(max_length=150)
    posted_at = models.DateField(null=True)
    job_type = models.CharField(max_length=150, null=True)
    experience_level = models.CharField(max_length=150, null=True)
    medium = models.CharField(max_length=150)
    link = models.URLField(max_length=500)

    def __str__(self):
        return self.title


class Application(models.Model):
    class ApplicationStatus(models.IntegerChoices):
        NoResponse = (0, 'No Response')
        VIEWED = (1, 'Viewed')
        CONTACTED = (2, 'Contacted')
        INTERVIEWED = (3, 'Interviewed')
        ACCEPTED = (4, 'Accepted')
        REJECTED = (5, 'Rejected')


    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    company = models.CharField(max_length=150)
    posted_at = models.DateField(null=True)
    applied_at = models.DateField()
    job_type = models.CharField(max_length=150, null=True)
    experience_level = models.CharField(max_length=150, null=True)
    medium = models.CharField(max_length=150)
    link = models.URLField(max_length=500)
    status = models.IntegerField(choices=ApplicationStatus.choices)

    def __str__(self):
        return self.title

report/forms.py
from django import forms

class AddApplicationForm(forms.Form):
    title = forms.CharField(max_length=150, required=True, label='Job Title', widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'type':'text'}))
    company = forms.CharField(max_length=150, required=True, label='Company', widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'type':'text'}))
    medium = forms.CharField(max_length=150, required=True, label='Where do you find this job?', widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'type':'text'}))
    link = forms.URLField(max_length=500, required=True, label='Job Link', widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'type':'url'}))
    job_type = forms.CharField(max_length=150, required=False, label='Job Type', widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'type':'text'}))
    level = forms.CharField(max_length=150, required=False, label='Experience Level', widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'type':'text'}))
    posted_at = forms.DateField(label='Job Posted', required=False, widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'type':'date'}))
    applied_at = forms.DateField(label='Applied at', required=False, widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'type':'date'}))

report/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from .forms import AddApplicationForm
from django.views.decorators.http import require_http_methods
from pprint import pprint
from .models import Application
from django.core import serializers
import json
import io
import xlsxwriter



def show(request):
    statistics = []
    statistics.append(Application.objects.filter(status=0).count())
    statistics.append(Application.objects.filter(status=1).count())
    statistics.append(Application.objects.filter(status=2).count())
    statistics.append(Application.objects.filter(status=3).count())
    statistics.append(Application.objects.filter(status=4).count())
    statistics.append(Application.objects.filter(status=5).count())

    return render(request, 'report/show.html', {'statistics': statistics})


def report_data(request):
    applications = request.user.application_set.all()

    #pprint(applications)
    response = serializers.serialize('json', applications)
    response = json.loads(response)
    return JsonResponse(response, safe=False)


@require_http_methods(["GET", "POST"])
def add_application(request):
    if request.method == 'POST':
        form = AddApplicationForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            
            request.user.application_set.create(
                title=data['title'],
                company=data['company'],
                medium=data['medium'],
                link=data['link'],
                job_type=data['job_type'],
                experience_level=data['level'],                
                posted_at=data['posted_at'],
                applied_at=data['applied_at'],
                status=0
            )

            return redirect('/report')

    else:
        form = AddApplicationForm()

    return render(request, 'report/add_application.html', {'form': form})


def change_status(request, pk):
    application = Application.objects.filter(pk=pk)
    application.update(status=request.POST['status'])

    return JsonResponse({'status': 200})



def export(request):
    output = io.BytesIO()
    workbook = xlsxwriter.Workbook(output)
    worksheet = workbook.add_worksheet()

    columns = ['#', 'Title', 'Company', 'Medium', 'Job Type', 'Experience Level',
    'Posted at', 'Applied at', 'Status']

    bold = workbook.add_format({'bold': True})

    for col_num in range(len(columns)):
        worksheet.write(0, col_num, columns[col_num], bold)

    data = request.user.application_set.all().values_list('id', 'title', 'company', 'medium', 'job_type', 'experience_level',
    'posted_at', 'applied_at', 'status', 'link')

    statuses = [
        ['No Response', '#808080'], 
        ['Viewed', '#800080'],
        ['Contacted', '#FF6600'],
        ['Interviewed', '#0000FF'],
        ['Accepted', '#008000'],
        ['Rejected', '#FF0000']
    ]
    
    row_num = 1

    for row in data:
        for col_num in range(len(columns)):
            if col_num == 1:
                cell_format = workbook.add_format({'font_color': 'blue'})
                worksheet.write_url(row_num, col_num, row[9], cell_format, string=row[col_num])
            elif col_num in [6,7]:
                cell_format = workbook.add_format({'num_format': 'mmm d yyyy'})
                worksheet.write(row_num, col_num, row[col_num], cell_format)
            elif col_num == 8:
                status = statuses[row[col_num]][0]
                cell_format = workbook.add_format({'bold': True, 'font_color': '#FFFFFF', 'bg_color': statuses[row[col_num]][1]})
                worksheet.write(row_num, col_num, status, cell_format)
            else:
                worksheet.write(row_num, col_num, row[col_num])
        row_num += 1


    worksheet.autofit()

    workbook.close()

    output.seek(0)

    filename = 'report.xlsx'
    response = HttpResponse(
        output,
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
    response['Content-Disposition'] = 'attachment; filename=%s' % filename

    return response

report/templates/report/add_application.html
{% extends 'base.html' %}
{% block content %}
<main>

    <div class="hero-area2 slider-height2 hero-overly2 d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center pt-50">
                        <h2>Add Application</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--Hero End -->
    <!--================Blog Area =================-->
    <section class="blog_area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-12 mb-5 mb-lg-0">
                    <div class="card shadow p-5">
                        <form method="POST" action="{% url 'report:add_application' %}">
                            {% csrf_token %}
                            {{ form.as_div }}
                            <button type="submit" class="btn btn-primary">Add</button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}

report/templates/report/show.html
{% extends 'base.html' %}
{% block content %}
<main>


    <!--Hero End -->
    <!--================Blog Area =================-->
    <section class="blog_area section-padding pt-0">
        <div class="p-5">

            <div style="width: 82%;" class="mx-auto">
                <div class="filters mb-5 mt-5 row" style="font-size: 30px;">
                    <div id="no_response" class="col card rounded p-3 mr-5 ml-5"
                        style="background-color: grey; color: white;">
                        <strong>No Response</strong>
                        <span>{{statistics.0}}</span>
                    </div>
                    <div id="viewed" class="col card rounded p-3 mr-5"
                        style="background-color: burlywood; color: white;">
                        <strong>Viewed</strong>
                        <span>{{statistics.1}}</span>
                    </div>
                    <div id="contacted" class="col card rounded p-3 mr-5"
                        style="background-color: orange; color: white;">
                        <strong>Contacted</strong>
                        <span>{{statistics.2}}</span>
                    </div>
                </div>

                <div class="filters mb-5 mt-5 row" style="font-size: 30px;">

                    <div id="interviewed" class="col card rounded p-3 mr-5 ml-5"
                        style="background-color: #1C82AD; color: white;">
                        <strong>Interviewed</strong>
                        <span>{{statistics.3}}</span>
                    </div>
                    <div id="accepted" class="col card rounded p-3 mr-5"
                        style="background-color: #367E18; color: white;">
                        <strong>Accepted</strong>
                        <span>{{statistics.4}}</span>
                    </div>
                    <div id="rejected" class="col card rounded p-3 mr-5"
                        style="background-color: #DC0000; color: white;">
                        <strong>Rejected</strong>
                        <span>{{statistics.5}}</span>
                    </div>
                </div>
            </div>

            <div class="row col-10 mx-auto">
                <div class="mb-5 mb-lg-0 col-12">
                    <table class="display" id="test" >
                        <thead>
                            <tr>
                                <th style="background-color: #144674; color: white;">#</th>
                                <th style="background-color: #144674; color: white;">Job Title</th>
                                <th style="background-color: #144674; color: white;">Company</th>
                                <th style="background-color: #144674; color: white;">Medium</th>
                                <th style="background-color: #144674; color: white;">Job Type</th>
                                <th style="background-color: #144674; color: white;">Experience Level</th>
                                <th style="background-color: #144674; color: white;">Job Posted at</th>
                                <th style="background-color: #144674; color: white;">Applied at</th>
                                <th style="background-color: #144674; color: white;">Status</th>
                                <th style="background-color: #144674; color: white;">Change Status</th>
                                <th style="background-color: #144674; color: white;"></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}

{% block extrascripts %}
<script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" language="javascript"
    src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" language="javascript"
    src="https://cdn.datatables.net/buttons/2.0.1/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" language="javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" language="javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script type="text/javascript" language="javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script type="text/javascript" language="javascript"
    src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.html5.min.js"></script>
<script type="text/javascript" language="javascript"
    src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.print.min.js"></script>
<script>
    $(document).ready(function () {
        let table = new DataTable('#test', {
            dom: 'lBftipr',
            scrollX: true,
            buttons: [
                {
                    text: 'Export',
                    className: 'ml-3',
                    action: function (e, dt, node, config) {
                        axios.get('/report/report/export', { responseType: 'blob' })
                            .then(response => {
                                console.log(response)
                                const href = URL.createObjectURL(new Blob([response.data]));

                                const link = document.createElement('a');
                                link.href = href;
                                link.setAttribute('download', 'report.xlsx');
                                document.body.appendChild(link);
                                link.click();

                                document.body.removeChild(link);
                                URL.revokeObjectURL(href);
                            })
                    }
                }
            ],
            ajax: {
                "processing": true,
                "url": "{% url 'report:report_data' %}",
                "dataSrc": "",
            },
            columns: [
                { "data": "pk" },
                { "data": "fields.title" },
                { "data": "fields.company" },
                { "data": "fields.medium" },
                { "data": "fields.job_type" },
                { "data": "fields.experience_level" },
                { "data": "fields.posted_at" },
                { "data": "fields.applied_at" },
                { "data": "fields.status" },
                { "data": "fields.status" },
                {
                    data: null,
                    className: "dt-center editor-edit",
                    defaultContent: '<i class="fa fa-pencil-alt"/><i class="fa fa-trash"/>',
                    orderable: false
                }
            ],
            columnDefs: [
                {
                    "targets": [1],
                    render: function (data, type, row) {
                        return `<a href="${row.fields.link}" style="color:black">${row.fields.title}</a>`
                    }
                },
                {
                    "targets": [8],
                    render: function (data, type, row) {
                        options = [
                            ['No Response', 'color:white;padding:5px; background-color: grey'],
                            ['Viewed', 'color:white;padding:5px; background-color: burlywood'],
                            ['Contacted', 'color:white;padding:5px; background-color: orange'],
                            ['Interviewed', 'color:white;padding:5px; background-color: #1C82AD'],
                            ['Accepted', 'color:white;padding:5px; background-color: #367E18'],
                            ['Rejected', 'color:white;padding:5px; background-color: #DC0000']
                        ]
                        i = row.fields.status
                        return `<span style="${options[i][1]}">${options[i][0]}</span>`
                    }
                },

                {
                    "targets": [9],
                    render: function (data, type, row) {
                        options = ['No Response', 'Viewed', 'Contacted', 'Interviewed', 'Accepted', 'Rejected']

                        select_options = ''
                        for (let i = 0; i < options.length; i++) {
                            if (i == row.fields.status) {
                                select_options += '<option value="' + i + '" selected>' + options[i] + '</option>'
                            } else {
                                select_options += '<option value="' + i + '">' + options[i] + '</option>'
                            }
                        }

                        return `<select onchange="test(this,${row.pk})">${select_options}</select>`
                    }
                }
            ]
        });

        $('#no_response').on('click', function () {
            let searchTerm = $(this).children('strong').text()
            console.log($(this).text())
            table
                .columns(8)
                .search(`\^${searchTerm}$`, true, false)
                .draw();
        });

        $('#viewed').on('click', function () {
            let searchTerm = $(this).children('strong').text()
            table
                .columns(8)
                .search(`\^${searchTerm}$`, true, false)
                .draw();
        });

        $('#contacted').on('click', function () {
            let searchTerm = $(this).children('strong').text()
            console.log($(this).text())
            table
                .columns(8)
                .search(`\^${searchTerm}$`, true, false)
                .draw();
        });

        $('#interviewed').on('click', function () {
            let searchTerm = $(this).children('strong').text()
            table
                .columns(8)
                .search(`\^${searchTerm}$`, true, false)
                .draw();
        });

        $('#accepted').on('click', function () {
            let searchTerm = $(this).children('strong').text()
            console.log($(this).text())
            table
                .columns(8)
                .search(`\^${searchTerm}$`, true, false)
                .draw();
        });

        $('#rejected').on('click', function () {
            let searchTerm = $(this).children('strong').text()
            table
                .columns(8)
                .search(`\^${searchTerm}$`, true, false)
                .draw();
        });
    });

    function test(element, id) {
        var status = element.options[element.selectedIndex].value
        var formData = new FormData()
        formData.append('status', status)

        axios.defaults.xsrfHeaderName = "X-CSRFToken"
        axios.defaults.xsrfCookieName = 'csrftoken'

        axios.post(`applications/${id}/change-status`, formData)
            .then(response => {
                if (response.data.status == 200) {
                    location.reload()
                }
            })
    }

</script>
{% endblock %}